### PR TITLE
fix: edit-preview fails on renamed documents

### LINKED ISSUE #326: Preview fails if document has just been renamed
Which is the default use case when creating a new page:
1. Create document
2. Add content
3. Rename from `Document` to something useful
4. Click _Preview_-> there's an error because the sidekick tries to preview the document under its old name

### PR DESCRIPTION
**Pull request by rofe**
Fix #326

### CODE REVIEW

File: src/sidekick/module.js [hunk 1]
```diff
@@ -896,35 +896,39 @@
...
-              // show detail message only in config update mode
-              sk.showModal({
-                css: 'modal-config-failure',
-                message: resp.error,
-                sticky: true,
-                level: 0,
-              });
-            } else {
-              console.error(resp);
+          sk.addEventListener('statusfetched', async () => {
```
Comment (tripodsan) [inline src/sidekick/module.js:899]: if I understand correctly, the preview-click now first fetches the status before performing the post. doesn't this make it feel more sluggish? especially on sharepoint edit-urls, where making the reverse lookup is slow.
I would only fetch the status again, on a 404.

**Review by tripodsan — APPROVED** [review]
