### PR TITLE
fix(extension): sidekick not showing on new docs

### LINKED ISSUE #209: [Extension] Sidekick not activated on _new_ word documents
**Description**
When you create a new document, the sidekick doesn't open

**Additional context**
the problem seems to be the url:

new document:
```
https://adobe.sharepoint.com/sites/CC-Express/_layouts/15/doc.aspx?sourcedoc=....
```

existing document:
```
https://adobe.sharepoint.com/:w:/r/sites/CC-Express/_layouts/15/Doc.aspx?sourcedoc=...
```

### suggestion

1. check if the url  has a type marker `/:w:/` or `/:x:/` in it, using `/\/:+:\//`
2. if yes, only allow `:w:` and `:x:`
3. if no, check if it's a document with `/\/doc?\.aspx\?/i`

### PR DESCRIPTION
**Pull request by rofe**
Fix #209

### CODE REVIEW

File: src/extension/utils.js [hunk 1]
```diff
@@ -118,7 +122,11 @@ export function getConfigMatches(configs, tabUrl, proxyUrl) {
         .some(([mpHost, mpPath]) => {
           if (checkHost === mpHost) {
             if (mpHost.endsWith('sharepoint.com')) {
-              if (!/^\/:[wx]:\/r\//.test(new URL(tabUrl).pathname)) {
+              const res = /^\/:(.+):\//.exec(pathname);
+              if (res && !'wx'.includes(res[1])) {
+                // editor url, but neither word nor excel
+                return false;
+              } else if (!/doc\d?\.aspx$/i.test(pathname) || !searchParams.has('sourcedoc')) {
```
Comment (tripodsan) [inline src/extension/utils.js:129]:
```suggestion
              } else if (!/\/doc\d?\.aspx$/i.test(pathname) || !searchParams.has('sourcedoc')) {
```

File: src/extension/utils.js [hunk 2]
```diff
@@ -118,7 +122,11 @@ export function getConfigMatches(configs, tabUrl, proxyUrl) {
         .some(([mpHost, mpPath]) => {
           if (checkHost === mpHost) {
             if (mpHost.endsWith('sharepoint.com')) {
-              if (!/^\/:[wx]:\/r\//.test(new URL(tabUrl).pathname)) {
+              const res = /^\/:(.+):\//.exec(pathname);
```
Comment (tripodsan) [inline src/extension/utils.js:125]:
```suggestion
              const res = /^\/:(.):\//.exec(pathname);
```

**Review by tripodsan — APPROVED** [review]
